// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44390' | (string & {});
};

export type GetEnabledData = {
    body?: never;
    path: {
        alias: string;
    };
    query?: never;
    url: '/umbraco/powertoys/api/v1/{alias}/enabled';
};

export type GetEnabledErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetEnabledResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type GetEnabledResponse = GetEnabledResponses[keyof GetEnabledResponses];

export type SetEnabledData = {
    body?: boolean;
    path: {
        alias: string;
    };
    query?: never;
    url: '/umbraco/powertoys/api/v1/{alias}/enabled';
};

export type SetEnabledErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type SetEnabledResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetSettingsData = {
    body?: never;
    path: {
        alias: string;
    };
    query?: never;
    url: '/umbraco/powertoys/api/v1/{alias}/settings';
};

export type GetSettingsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetSettingsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type SaveSettingsData = {
    body?: unknown;
    path: {
        alias: string;
    };
    query?: never;
    url: '/umbraco/powertoys/api/v1/{alias}/settings';
};

export type SaveSettingsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type SaveSettingsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/powertoys/api/v1/ping';
};

export type PingErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PingResponses = {
    /**
     * OK
     */
    200: string;
};

export type PingResponse = PingResponses[keyof PingResponses];
