// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44377' | (string & {});
};

export type GetEnabledData = {
    body?: never;
    path: {
        alias: string;
    };
    query?: never;
    url: '/umbraco/powertoys/api/v1/{alias}/enabled';
};

export type GetEnabledErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetEnabledResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type GetEnabledResponse = GetEnabledResponses[keyof GetEnabledResponses];

export type SetEnabledData = {
    body?: boolean;
    path: {
        alias: string;
    };
    query?: never;
    url: '/umbraco/powertoys/api/v1/{alias}/enabled';
};

export type SetEnabledErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type SetEnabledResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetSettingsData = {
    body?: never;
    path: {
        alias: string;
    };
    query?: never;
    url: '/umbraco/powertoys/api/v1/{alias}/settings';
};

export type GetSettingsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetSettingsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type SaveSettingsData = {
    body?: unknown;
    path: {
        alias: string;
    };
    query?: never;
    url: '/umbraco/powertoys/api/v1/{alias}/settings';
};

export type SaveSettingsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type SaveSettingsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetBackupData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/powertoys/api/v1/backup';
};

export type GetBackupErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetBackupResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type GetBackupResponse = GetBackupResponses[keyof GetBackupResponses];

export type RestoreBackupData = {
    body?: {
        [key: string]: string;
    };
    path?: never;
    query?: never;
    url: '/umbraco/powertoys/api/v1/backup';
};

export type RestoreBackupErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type RestoreBackupResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUrlData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/powertoys/api/v1/media/{id}/url';
};

export type GetUrlErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetUrlResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetUrlResponse = GetUrlResponses[keyof GetUrlResponses];

export type PingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/powertoys/api/v1/ping';
};

export type PingErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PingResponses = {
    /**
     * OK
     */
    200: string;
};

export type PingResponse = PingResponses[keyof PingResponses];
