<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <StaticWebAssetBasePath>/</StaticWebAssetBasePath>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>Umbraco.Community.PowerToys</PackageId>
    <Product>Umbraco.Community.PowerToys</Product>
    <Title>Umbraco Community PowerToys</Title>
    <Description>A collection of small, extendable tools for the Umbraco backoffice.</Description>
    <PackageTags>umbraco umbraco-marketplace umbraco-cms</PackageTags>
    <Authors>Jumoo</Authors>
    <Copyright>$([System.DateTime]::UtcNow.ToString(`yyyy`)) © Jumoo</Copyright>
    <PackageProjectUrl>https://github.com/jumoo/umbraco.community.powertoys</PackageProjectUrl>
    <RepositoryUrl>https://github.com/jumoo/umbraco.community.powertoys</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README_nuget.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\docs\README_nuget.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>


  <!-- Central package management - no versions -->
  <ItemGroup>
    <PackageReference Include="Umbraco.Cms.Api.Common" />
    <PackageReference Include="Umbraco.Cms.Api.Management" />
    <PackageReference Include="Umbraco.Cms.Web.Common" />
    <PackageReference Include="Umbraco.Cms.Web.Website" />
  </ItemGroup>


  <ItemGroup>
    <!-- Don't include the client folder as part of packaging nuget build -->
    <Content Remove="Client\**" />

    <!-- However make the Umbraco-package.json included for dotnet pack or nuget package and visible to the solution -->
    <None Include="Client\public\umbraco-package.json" Pack="false" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

</Project>
