name: PR Project Build

on:
  pull_request:
    branches: ["v17/main"]
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: src/PowerToys/Client/package-lock.json

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Build client
        working-directory: src/PowerToys/Client
        run: |
          npm ci
          npm run build

      - name: Restore
        run: dotnet restore src/PowerToys/PowerToys.csproj --locked-mode

      - name: Build
        run: dotnet build src/PowerToys/PowerToys.csproj -c Release --no-restore -p:ContinuousIntegrationBuild=true
